
export default function() {
  var data = {
    id: 'comparator0',
    name: 'Comparator',
    children: [{"name":"sites","code":"sites","id":"comparator1","colname":"comparator"},{"name":"None","code":"None","id":"comparator2","colname":"comparator"},{"name":"Presence/Absence of intervention","code":"Presence/Absence of intervention","id":"comparator3","colname":"comparator"},{"name":"user groups","code":"user groups","id":"comparator4","colname":"comparator"},{"name":"socio-economic","code":"socio-economic","id":"comparator5","colname":"comparator"},{"name":"presence/absence of intervention","code":"presence/absence of intervention","id":"comparator6","colname":"comparator"},{"name":"projects","code":"projects","id":"comparator7","colname":"comparator"},{"name":"socio-economic groups","code":"socio-economic groups","id":"comparator8","colname":"comparator"},{"name":"cultural/ethnic groups","code":"cultural/ethnic groups","id":"comparator9","colname":"comparator"},{"name":"Presence/absence of intervention","code":"Presence/absence of intervention","id":"comparator10","colname":"comparator"},{"name":"demographic groups","code":"demographic groups","id":"comparator12","colname":"comparator"},{"name":"Unspecified","code":"Unspecified","id":"comparator13","colname":"comparator"},{"name":"project","code":"project","id":"comparator14","colname":"comparator"},{"name":"User groups","code":"User groups","id":"comparator15","colname":"comparator"},{"name":"Sites","code":"Sites","id":"comparator16","colname":"comparator"},{"name":"Socio-economic groups/levels","code":"Socio-economic groups/levels","id":"comparator17","colname":"comparator"},{"name":"Projects","code":"Projects","id":"comparator18","colname":"comparator"},{"name":"Demographic groups","code":"Demographic groups","id":"comparator19","colname":"comparator"},{"name":"Cultural/ethnic groups","code":"Cultural/ethnic groups","id":"comparator20","colname":"comparator"},{"name":"","code":"","id":"comparator21","colname":"comparator"},{"name":"NA","code":"NA","id":"comparator21","colname":"comparator"}]
  };
  return data;
}
